import Head from 'next/head'
import styled from 'styled-components'
import { useEffect, useState } from 'react'
import gameApi from '../src/api/game'
import { videoGame } from '@/src/types/video-game'
import Tile from '@/src/components/Tile/tile'
import SearchBar from '@/src/components/SearchBar/searchBar'
import GameView from '@/src/components/GameView/gameView'

export default function Home() {
  const [games, setGames] = useState<videoGame[]>([])
  const [searchedGame, setSearchedGame] = useState<videoGame>()
  const [openModal, setOpenModal] = useState(false)

  useEffect(() => {
    const getGame = async () => {
      const gamesResponse = await gameApi.getPopular()
      if (gamesResponse !== undefined) {
        setGames(gamesResponse)
      }
    }
    getGame()
  }, [])

  const searchForGame = async (game: string) => {
    const getGame = await gameApi.getGame(game)

    setSearchedGame(getGame)
    console.log(searchedGame)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <h1>Game Critic</h1>
        <SearchBar onEnter={searchForGame} />
        {openModal && <GameView openModal={setOpenModal} />}
        {searchedGame?.name !== undefined && (
          <Tile
            name={searchedGame.name}
            background_image={searchedGame.background_image}
            description_raw={searchedGame.description_raw}
            onClick={() => setOpenModal(true)}
          />
        )}
        <Line />
        <h2>The Latest Games</h2>
        <TileWrapper>
          {games.map((game) => (
            <Tile
              onClick={() => setOpenModal(true)}
              name={game.name}
              background_image={game.background_image}
              description_raw={game.description_raw}
            />
          ))}
        </TileWrapper>
      </Main>
    </>
  )
}

const Main = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: center;
  padding: 6rem;
`

const Line = styled.span`
  width: 100%;
  margin: 16px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.3);
`

const TileWrapper = styled.div`
  overflow-y: none;
  display: grid;
  gap: 16px;
  grid-template-columns: repeat(5, 1fr);
`
